### ISSUE TITLE
Does this fork remove ffprobe?

### ISSUE THREAD

**Issue by Aditya94A** [tsoumalis/FFmpeg-Android#1]
I couldn't get ignoreAssetsPattern to get rid of ffprobe + give one arch arm or x86, so I went to fork and manually remove ffprobe from @bravobit's repo and lo and behold here I see another fork with a commit that says "removed ffprobe"

Can you please shed some light on how this fork is different? You're just removing ffprobe? Exactly what differences in compilation params have you chosen for ffmpeg? Have you noticed in performance differences in building specifically for arm64 as well?

**Comment by tsoumalis** [comment]
Yes, ffprobe is removed in this version. The ffmpeg binaries are also built to be much smaller in size (which removes a few capabilities but cover most usage cases). The build configuration with supported encoders, decoders etc. can be found in the readme file. The size of each executable is ~8MB instead of 19MB in the release from @bravobit. I also do not use libfdk-aac due to licensing limitations.

The arm64 build has significantly improved performance when it comes to audio processing (about 10x faster encoding/decoding performance with libmp3lame and aac). The difference in encoding speed is also noticable with libx264 but it is not much faster. In this build libx264 displays ARMv8 capabilities (instead of ARMv6) but it has slight performance boost.

This configuration was one that suits my needs for reduced APK size and ARM only support in a production application (x86 is also removed in case you didn't notice) and I decided to share it in case someone else could benefit from it or collaborate to improve it furthermore.

My plan is to update this frequently with the newest FFmpeg builds that I also use in my production application.
