### ISSUE TITLE
Any reasons for using --enable-static?

### ISSUE THREAD

**Issue by danilogr** [tsoumalis/FFmpeg-Android#2]
Hey, first, thanks for making your cross-compilation flags available to everyone. 
Is there any reason for building static libraries instead of shared libraries?

**Comment by tsoumalis** [comment]
Hello,

The main reason for this is the fact that the target of this project is to produce the ffmpeg executable, which requires the static libraries to be built instead of the shared. 

In the sample you can see that the executable is being used with parametres. With shared libraries, it would require to create a libffmpeg.so with custom C++ code to be able to call main(). This is a different approach that is used by some other similar projects here on GitHub, but my goal was to produce the static executable from the beginning, and that is why I forked the project from bravobit.

**Comment by danilogr** [comment]
Gotcha. Thanks!
